### PR TITLE
Remove sorted hash

### PR DESCRIPTION
**Pull request by Phil-Friderici**
should be complete now :)

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
I am confused now, did I delete it by accident ?
This PR removes the sorted hash template.

**Comment by ghoneycutt** [comment]
Great work! Thanks!

**Comment by ghoneycutt** [comment]
We could use the puppet-strings inline docs like the Sensu module if you've got time :>

**Comment by Phil-Friderici** [comment]
There we go: https://github.com/ghoneycutt/sgnl05-sssd/pull/4

**Pull request merged**
